bruin = set(["Boxtel","Best","Beukenlaan","Helmond 't Hout","Helmond","Helmond Brouwhuis","Deurne"])
groen  = set(["Boxtel","Best","Beukenlaan","Geldrop","Heeze","Weert"])
print(bruin.intersection(groen))
print(bruin.difference(groen))
print(bruin.union(groen))
